using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestDb2App.DTO
{
    public class F101
    {
        public string ABSTAT { get; set; }  // A(1)
        public string ABPRFX { get; set; }  // A(1)
        public string ABNO { get; set; }    // A(6)
        public string ABALPH { get; set; }  // A(25)
        public string ABALNM { get; set; }  // A(30)
        public int? ABAREA { get; set; }    // P(3,0)
        public int? ABPHON { get; set; }    // P(7,0)
        public string ABEXT1 { get; set; }  // A(4)
        public int? ABARA2 { get; set; }    // P(3,0)
        public int? ABPHN2 { get; set; }    // P(7,0)
        public string ABEXT2 { get; set; }  // A(4)
        public string ABD01 { get; set; }   // A(3)
        public string ABD02 { get; set; }   // A(3)
        public string ABD03 { get; set; }   // A(3)
        public string ABD04 { get; set; }   // A(3)
        public string ABD05 { get; set; }   // A(3)
        public string ABD06 { get; set; }   // A(3)
        public string ABD07 { get; set; }   // A(3)
        public string ABD08 { get; set; }   // A(3)
        public string ABD09 { get; set; }   // A(3)
        public string ABD10 { get; set; }   // A(3)
        public string ABSTCD { get; set; }  // A(2)
        public string ABZIP { get; set; }   // A(9)
        public string ABSIC { get; set; }   // A(5)
        public string ABPADR { get; set; }  // A(7)
        public string ABSAD1 { get; set; }  // A(7)
        public string ABSAD2 { get; set; }  // A(7)
        public string ABVTYP { get; set; }  // A(1)
        public string ABCHEK { get; set; }  // A(1)
        public string ABTAXC { get; set; }  // A(1)
        public string ABSTMT { get; set; }  // A(1)
        public string ABSTTO { get; set; }  // A(1)
        public string ABABC1 { get; set; }  // A(1)
        public string ABABC2 { get; set; }  // A(1)
        public string ABABC3 { get; set; }  // A(1)
        public string ABTRAP { get; set; }  // A(1)
        public string ABTRAR { get; set; }  // A(1)
        public string ABLATE { get; set; }  // A(1)
        public string ABFWRD { get; set; }  // A(1)
        public string ABCRRP { get; set; }  // A(1)
        public string ABCKHC { get; set; }  // A(1)
        public string ABVEND { get; set; }  // A(1)
        public string ABCUST { get; set; }  // A(1)
        public string ABEMP { get; set; }   // A(1)
        public string ABPRRP { get; set; }  // A(1)
        public string ABNONT { get; set; }  // A(1)
        public string ABPRCH { get; set; }  // A(1)
        public string ABIPRT { get; set; }  // A(1)
        public string ABKEYF { get; set; }  // A(1)
        public string ABPRCS { get; set; }  // A(1)
        public string ABRETP { get; set; }  // A(1)
        public string ABRMTF { get; set; }  // A(1)
        public string ABICST { get; set; }  // A(1)
        public string ABFBDR { get; set; }  // A(1)
        public string ABUPNM { get; set; }  // A(7)
        public string ABLONM { get; set; }  // A(7)
        public string ABKEYC { get; set; }  // A(1)
        public string ABSNDC { get; set; }  // A(1)
        public string ABSNDN { get; set; }  // A(1)
        public string ABSNDS { get; set; }  // A(1)
        public string ABCALL { get; set; }  // A(1)
        public string ABPSHP { get; set; }  // A(1)
        public string ABIPFX { get; set; }  // A(3)

        public decimal? ABTAX { get; set; }   // P(9,0)
        public decimal? ABFLOT { get; set; }  // P(3,0)
        public decimal? ABPAID { get; set; }  // P(9,2)
        public decimal? ABPYPD { get; set; }  // P(9,2)
        public decimal? ABBNCG { get; set; }  // P(5,2)
        public decimal? ABCRED { get; set; }  // P(7,0)
        public decimal? ABSYTD { get; set; }  // P(9,0)
        public decimal? ABCYTD { get; set; }  // P(9,0)
        public decimal? ABOYTD { get; set; }  // P(3,0)
        public decimal? ABSPYE { get; set; }  // P(9,0)
        public decimal? ABCPYE { get; set; }  // P(9,0)
        public decimal? ABOPYE { get; set; }  // P(3,0)
        public decimal? ABCDUE { get; set; }  // P(11,2)
        public decimal? ABASLC { get; set; }  // P(9,2)
        public decimal? ABLCBL { get; set; }  // P(7,2)
        public decimal? ABHIBL { get; set; }  // P(9,0)
        public decimal? ABLPAM { get; set; }  // P(9,2)
        public decimal? ABDUES { get; set; }  // P(7,2)

        public DateTime? ABDTCR { get; set; } // L(10)
        public DateTime? ABDTFI { get; set; } // L(10)
        public DateTime? ABDTLI { get; set; } // L(10)
        public DateTime? ABHIDT { get; set; } // L(10)
        public DateTime? ABLPDT { get; set; } // L(10)
    }

}
